PAGES = {"introduction": """In "The Library of Babel," Borges conceives of a library composed of an uncountable number of hexagonal rooms filled with books. The Library is "'total'--perfect, complete, and whole--and [...] its bookshelves contain all possible combinations of the twenty-two orthographic symbols (a number which, though unimaginably vast, is not infinite)--that is, all that is able to be expressed, in every language." The interface you are looking at now allows you to explore a modern interpretation of Borges' Library of Babel, which is mostly faithful to the story except for one major change. Borges's library was limited to the 22 symbols used in predominantly European languages. To truly express "all that is able to be expressed," this library contains every possible sequence of binary digits (of length 32000). Each page can be read as utf-32, but you may notice that pages that are meaningful to the human eye make up an unfathomable minority of all of the pages that the library contains.              """,
        "Genesis": """As people moved eastward, they found a plain in Shinar and settled there. They said to each other, Come, let’s make bricks and bake them thoroughly. They used brick instead of stone, and tar for mortar. Then they said, Come, let us build ourselves a city, with a tower that reaches to the heavens, so that we may make a name for ourselves; otherwise we will be scattered over the face of the whole earth. But the Lord came down to see the city and the tower the people were building. The Lord said, If as one people speaking the same language they have begun to do this, then nothing they plan to do will be impossible for them. Come, let us go down and confuse their language so they will not understand each other. So the Lord scattered them from there over all the earth, and they stopped building the city. That is why it was called Babel—because there the Lord confused the language of the whole world. From there the Lord scattered them over the face of the whole earth.""",
        "道德经": """道可道,非常道。
名可名,非常名。
無名天地之始;有名萬物之母。
故常無欲,以觀其妙;常有欲,以觀其徼。
此兩者,同出而異名,同謂之玄。
玄之又玄,衆妙之門。""",
        "Borges": """For every rational line or forthright statement there are leagues of senseless cacophony, verbal nonsense, and incoherency. [...]
For many years it was believed that those impenetrable books were in ancient or far-distant languages. It is true that the most ancient peoples, the first librarians, employed a language quite different from the one we speak today; it is true that a few miles to the right, our language devolves into dialect and that ninety floors above, it becomes incomprehensible. All of that, I repeat, is true--but four hundred ten pages of unvarying M C V's cannot belong to any language, however dialectal or primitive it may be. Some have suggested that each letter influences the next, and that the value of M C V on page 71, line 3, is not the value of the same series on another line of another page [...] Others have mentioned the possibility of codes; that conjecture has been universally accepted, though not in the sense in which its originators formulated it. """,
        "musings": "it was a dark and stormy night",
        "the answer": "42",
        "source code": "defconvertToBase(x,base,language=None):ifbase==36:digs=string.digits+'abcdefghijklmnopqrstuvwxyz'elifbase==10:digs='0123456789'elifbase==60:digs='0123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz'else:charset_start=languages[language][0]charset_end=languages[language][1]+1charset_length=charset_end-charset_startdigs=[chr(x)forxinrange(charset_start,charset_end+1)]ifx<0:sign=-1elifx==0:returndigs[0]else:sign=1x*=signchars=[]whilex:remainder=x%basechars.append(digs[remainder])x//=baseifsign<0:chars.append('-')chars.reverse()return''.join(chars)",
        "project acknowledgements": "The underlying code for this library is a modification of the algorithm implemented by louis-e (repository at https://github.com/louis-e/LibraryOfBabel-Python). Initial inspiration was taken from the Library of Babel website created by Jonathan Basille (https://libraryofbabel.info/), and, of course, the original short story by Jorge Luis Borges. The interface is built through the Textual python framework (https://textual.textualize.io/). I also received valuable help, feedback, and advice from friends at the Recurse Center in the summer of 2025, especially Claire Froelich (https://clairefro.dev/)."}